server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: springappuser
          uri: http://localhost:8085
          predicates:
            - Path=/api/users/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"


# logging.level.org.springframework.security=DEBUG
# logging.level.org.springframework.web=DEBUG
  
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: 
